# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bd4442b5fc85c4f3921a9da5fe139a15a258acc61d4fdcbc331b4ff367b20d437433e271276c0997b7ba5085c5120996acb18b640fb440854ee325692c98bff

test:
  secret_key_base: d50b44b1d7de8ce7fae0351b2a158e5f4a93fc358a35a73b16c340bb2de6700aea598194bb8acf580b93a0e489e90b5b9772b11b2b229d231046fe3c739e6287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
